const mongoose=require('mongoose');
const doctorSchema=new mongoose.Schema(
    {
    userId:{
    type:String,
    required:true,
    },
    firstName:{
    type:String,
    required:true,
    },
    lastName:{
        type:String,
        required:true,
    },
    phoneNo:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    },
    specialization:{
        type:String,
        required:true,
    },
    experience:{
        type:String,
        required:true,
    },
    feeForconsult:{
        type:Number,
        required:true,
    },
    timings:{
        type:Array,
        required:true,
    },
    status:{
        type:String,
        default:'Pending',
    },
},
{
    timestamps:true
}
);
const doctorModel=mongoose.model("doctors",doctorSchema);
module.exports=doctorModel;